// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Server2Client.proto

#ifndef PROTOBUF_Server2Client_2eproto__INCLUDED
#define PROTOBUF_Server2Client_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Server2Client_2eproto();
void protobuf_AssignDesc_Server2Client_2eproto();
void protobuf_ShutdownFile_Server2Client_2eproto();

class S2C_Test;
class S2C_Hello;

// ===================================================================

class S2C_Test : public ::google::protobuf::Message {
 public:
  S2C_Test();
  virtual ~S2C_Test();

  S2C_Test(const S2C_Test& from);

  inline S2C_Test& operator=(const S2C_Test& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_Test& default_instance();

  void Swap(S2C_Test* other);

  // implements Message ----------------------------------------------

  S2C_Test* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2C_Test& from);
  void MergeFrom(const S2C_Test& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required string str = 2;
  inline bool has_str() const;
  inline void clear_str();
  static const int kStrFieldNumber = 2;
  inline const ::std::string& str() const;
  inline void set_str(const ::std::string& value);
  inline void set_str(const char* value);
  inline void set_str(const char* value, size_t size);
  inline ::std::string* mutable_str();
  inline ::std::string* release_str();
  inline void set_allocated_str(::std::string* str);

  // @@protoc_insertion_point(class_scope:S2C_Test)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_str();
  inline void clear_has_str();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* str_;
  ::google::protobuf::int32 id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_Server2Client_2eproto();
  friend void protobuf_AssignDesc_Server2Client_2eproto();
  friend void protobuf_ShutdownFile_Server2Client_2eproto();

  void InitAsDefaultInstance();
  static S2C_Test* default_instance_;
};
// -------------------------------------------------------------------

class S2C_Hello : public ::google::protobuf::Message {
 public:
  S2C_Hello();
  virtual ~S2C_Hello();

  S2C_Hello(const S2C_Hello& from);

  inline S2C_Hello& operator=(const S2C_Hello& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_Hello& default_instance();

  void Swap(S2C_Hello* other);

  // implements Message ----------------------------------------------

  S2C_Hello* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const S2C_Hello& from);
  void MergeFrom(const S2C_Hello& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string ss = 1;
  inline int ss_size() const;
  inline void clear_ss();
  static const int kSsFieldNumber = 1;
  inline const ::std::string& ss(int index) const;
  inline ::std::string* mutable_ss(int index);
  inline void set_ss(int index, const ::std::string& value);
  inline void set_ss(int index, const char* value);
  inline void set_ss(int index, const char* value, size_t size);
  inline ::std::string* add_ss();
  inline void add_ss(const ::std::string& value);
  inline void add_ss(const char* value);
  inline void add_ss(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& ss() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_ss();

  // @@protoc_insertion_point(class_scope:S2C_Hello)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::std::string> ss_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_Server2Client_2eproto();
  friend void protobuf_AssignDesc_Server2Client_2eproto();
  friend void protobuf_ShutdownFile_Server2Client_2eproto();

  void InitAsDefaultInstance();
  static S2C_Hello* default_instance_;
};
// ===================================================================


// ===================================================================

// S2C_Test

// required int32 id = 1;
inline bool S2C_Test::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void S2C_Test::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void S2C_Test::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void S2C_Test::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 S2C_Test::id() const {
  return id_;
}
inline void S2C_Test::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required string str = 2;
inline bool S2C_Test::has_str() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void S2C_Test::set_has_str() {
  _has_bits_[0] |= 0x00000002u;
}
inline void S2C_Test::clear_has_str() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void S2C_Test::clear_str() {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    str_->clear();
  }
  clear_has_str();
}
inline const ::std::string& S2C_Test::str() const {
  return *str_;
}
inline void S2C_Test::set_str(const ::std::string& value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void S2C_Test::set_str(const char* value) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(value);
}
inline void S2C_Test::set_str(const char* value, size_t size) {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  str_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2C_Test::mutable_str() {
  set_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    str_ = new ::std::string;
  }
  return str_;
}
inline ::std::string* S2C_Test::release_str() {
  clear_has_str();
  if (str_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = str_;
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void S2C_Test::set_allocated_str(::std::string* str) {
  if (str_ != &::google::protobuf::internal::kEmptyString) {
    delete str_;
  }
  if (str) {
    set_has_str();
    str_ = str;
  } else {
    clear_has_str();
    str_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// S2C_Hello

// repeated string ss = 1;
inline int S2C_Hello::ss_size() const {
  return ss_.size();
}
inline void S2C_Hello::clear_ss() {
  ss_.Clear();
}
inline const ::std::string& S2C_Hello::ss(int index) const {
  return ss_.Get(index);
}
inline ::std::string* S2C_Hello::mutable_ss(int index) {
  return ss_.Mutable(index);
}
inline void S2C_Hello::set_ss(int index, const ::std::string& value) {
  ss_.Mutable(index)->assign(value);
}
inline void S2C_Hello::set_ss(int index, const char* value) {
  ss_.Mutable(index)->assign(value);
}
inline void S2C_Hello::set_ss(int index, const char* value, size_t size) {
  ss_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* S2C_Hello::add_ss() {
  return ss_.Add();
}
inline void S2C_Hello::add_ss(const ::std::string& value) {
  ss_.Add()->assign(value);
}
inline void S2C_Hello::add_ss(const char* value) {
  ss_.Add()->assign(value);
}
inline void S2C_Hello::add_ss(const char* value, size_t size) {
  ss_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
S2C_Hello::ss() const {
  return ss_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
S2C_Hello::mutable_ss() {
  return &ss_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Server2Client_2eproto__INCLUDED
